JSR 354 Money & Currency TCK User Guide
=======================================
Anatole Tresch <atsticks@gmail.com>
:Author Initials: ATR
:source-highlighter: coderay
:toc:
:icons:
:numbered:
:website: http://javamoney.org/
:imagesdir: src\main\asciidoc\images
:iconsdir: src\main\asciidoc\images/icons
:data-uri:

---------------------------------------------------------------------------------------------------
Copyright (c) 2012, 2013, Werner Keil, Credit Suisse (Anatole Tresch). Licensed under the Apache
License, Version 2.0 (the "License"); you may not use this file except in compliance with the
License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License
is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
or implied. See the License for the specific language governing permissions and limitations under
the License. Contributors: Anatole Tresch - initial version.
---------------------------------------------------------------------------------------------------

JSR 354 'Java Money' defines the Java API for managing monetary amounts and currencies in Java. As other
JSRs beside the reference implementations also other third parties can provide their implementations. This document will
describe how this technical compatibility kit (TCK) can be configured and used to determine the compatibility of an
implementation with the specification and reference implementation.

.This document
**********************************************************************
This is a user guide that describes all relevant aspects of the JSR 354
Java Money TCK, for using this TCK with any reference implementation.

**********************************************************************


Introduction to Java Money
--------------------------

[NOTE]
You may also read the JSR 354 API specification available https://jcp.org/en/jsr/detail?id=354[here].

Overview
~~~~~~~~

The technical compatibility kit (TCK) of a JSR ensures that implementations of a JSR implement the specification
correctly and help to ensure also behavioural interoperability between different implementations. So the
TCK for JSR 354 Money and Currency ensures exactly this for implementations of the Money & Currency JSR.
The TCK hereby is open sourced under the Apache 2 licence. Nevertheless we would be highly interested to keep track of
implementation of this JSR. So if you are are planning or even writing on an implementation of this JSR, drop a mail to
the JSR's mailto:jcurrency_mail@javamoney.java.net[mailing list] on http://java.net/project/JavaMoney[java.net] or the
JSR's mailto:atsticks@java.net[spec lead].


Downloading and Installing
~~~~~~~~~~~~~~~~~~~~~~~~~~

Basically the JSR 354 API as well as the TCK and its dependencies are available as maven artifacts. Additionally you
should of course also include the implementation to test:

[source, xml]
.Required Dependencies
---------------------------------------------------------------------------------------
<dependency>
    <groupId>org.javamoney</groupId>
    <artifactId>money-tck</artifactId>
    <version>${tck.version}</version>
</dependency>
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>6.8.5</version>
</dependency>
<dependency>
    <groupId>${impl.groupId}</groupId>
    <artifactId>${impl.artifactId}</artifactId>
    <type>${impl.packageType}</type>
    <version>${impl.version}</version>
</dependency>
---------------------------------------------------------------------------------------

Also we have added an https://github.com/JavaMoney/jsr354-ritest[example maven project] that can be used as a starting
point. All you have to do is clone it from https://github.com/JavaMoney/jsr354-ritest[GitHub] and exchange the
implementation under test with your own.

Main Design Decisions
~~~~~~~~~~~~~~~~~~~~~

Basically the TCK is a set of tests executed with TestNG. Basic reason for using TestNG is that this library also is
used in OpenJDK. Additionally in case of tests are failing you should see a detailed message and a reference to the
according section in the specification. The audit of the test coverage can be found
https://github.com/JavaMoney/jsr354-tck/blob/master/coverage-report[here].

Component Loading and Bootstrapping
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The TCK itself is built as a self-executable TestNG program. To execute the TCK basically two prerequisites are
necessary:
. you must have all required libraries on the classpath. This includes the JSR's API, your implementation under test,
  the TCK and TestNG, including all required dependencies.
. You have to provide a small class, implementing the +org.javamoney.tck.JSR354TestConfiguration+ interface and
  register it with the JDK's +java.util.ServiceLoader+ mechanism.

This can be achieved in different ways:

* The most easiest way to run the tests is to create a small maven project, where you add the JSR 354 API, your
implementation and the TCK as dependency. The only thing to be done is executing the test suite by running
+org.javamoney.tck.TCKRunner.main+.
* Or you can execute the TCK by starting it on the console:

[source, listing]
.Running the TCK
---------------------------------------------------------------------------------------
java -cp ... org.javamoney.tck.TCKRunner
---------------------------------------------------------------------------------------

The org.javamoney.tck.JSR354TestConfiguration Interface
-------------------------------------------------------

As mentioned before it is required that you implement an instance of the TCK's
+org.javamoney.tck.JSR354TestConfiguration+ interface:

[source, java]
.Interface JSR354TestConfiguration
---------------------------------------------------------------------------------------
/**
 * Libraries that implement this JSR and want to be tested with this TCK must implement this
 * interface and register it using the {@link ServiceLoader}.
 *
 * @author Anatole Tresch
 */
public interface JSR354TestConfiguration{

    /**
     * Return a collection with all {@link MonetaryAmount} classes that are implemented. The list
     * must not be empty and should contain <b>every</b> amount class implemented.<br/>
     * This enables the TCK to check in addition to the basic implementation compliance, if
     * according {@link MonetaryAmountFactoryProviderSpi} are registered/available correctly.
     *
     * @return a collection with all implemented amount classes, not null.
     */
    Collection<Class> getAmountClasses();

    /**
     * List a collection of {@link CurrencyUnit} implementation.<br/>
     * This enables the TCK to check the basic implementation compliance,
     *
     * @return
     */
    Collection<Class> getCurrencyClasses();


    /**
     * This method allows to let instances of MonetaryOperator to be tested for requirements and recommendations.
     *
     * @return the list of operators to be checked, not null. It is allowed to return an empty list here, which will
     * disable TCK tests for MonetaryOperator instances.
     */
    Collection<MonetaryOperator> getMonetaryOperators4Test();

}
---------------------------------------------------------------------------------------

Following find the example implementation ised for testing the reference implementation:

[source,java]
.TestSetup for the Moneta Reference Implementation
---------------------------------------------------------------------------------------
/**
 * Created by Anatole on 14.06.2014.
 */
public final class MonetaTCKSetup implements JSR354TestConfiguration{

    @Override
    public Collection<Class> getAmountClasses() {
            return Arrays
                    .asList(new Class[]{FastMoney.class,FastMoney.class});
    }

    @Override
    public Collection<Class> getCurrencyClasses() {
        try{
            return Arrays
                    .asList(new Class[] { Class.forName("org.javamoney.moneta.internal.JDKCurrencyAdapter")});
        }
        catch(ClassNotFoundException e){
            e.printStackTrace();
            throw new RuntimeException("Currency class not lodable: org.javamoney.moneta.internal.JDKCurrencyAdapter");
        }
    }

    @Override
    public Collection<MonetaryOperator> getMonetaryOperators4Test(){
        List<MonetaryOperator> ops = new ArrayList<>();
        ops.add(MonetaryFunctions.majorPart());
        ops.add(MonetaryFunctions.minorPart());
        ops.add(MonetaryFunctions.percent(BigDecimal.ONE));
        ops.add(MonetaryFunctions.percent(3.5));
        ops.add(MonetaryFunctions.permil(10.3));
        ops.add(MonetaryFunctions.permil(BigDecimal.ONE));
        ops.add(MonetaryFunctions.permil(10.5, MathContext.DECIMAL32));
        ops.add(MonetaryFunctions.reciprocal());
        ops.add(MonetaryRoundings.getRounding());
        ops.add(MonetaryConversions.getConversion("EUR"));
        return ops;
    }

}
---------------------------------------------------------------------------------------

You must register your implementation with the +java.util.ServiceLoader+. This can be achieved by adding the
following configuration file to your classpath:

[source, listing]
.Configuring the TCK Test Setup
---------------------------------------------------------------------------------------
META-INF
  \_ services
      \_ org.javamoney.tck.JSR354TestConfiguration
---------------------------------------------------------------------------------------

The 'org.javamoney.tck.JSR354TestConfiguration' file should contain exactly one line with the fully qualified
class name of your implementation provided:

[source, listing]
.Contents of the org.javamoney.tck.JSR354TestConfiguration file
---------------------------------------------------------------------------------------
com.mycomp.mymoney-lib.TCKSetup
---------------------------------------------------------------------------------------



Checking the Results
~~~~~~~~~~~~~~~~~~~~

Test execution is logged verbosely on the runtime console. Additionally after TCK execution you should find a folder
+tck-results+ within your working directory, containing the TestNG result in html (index.html) or xml format.

Contacts
~~~~~~~~

Basically you can use the JSR's public mailing list to get in contact or write an email to the JSR's mailto:atsticks@java.net[spec lead].